spring.application.name=bootcamp-films
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:films_db
spring.datasource.username=henrique
spring.datasource.password=123456
spring.datasource.driverClassName=org.h2.Driver

spring.h2.console.path=/h2-console