spring.application.name=bootcamp-films
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:file:./data/filmesdb

spring.datasource.username=henrique
spring.datasource.password=123456
spring.datasource.driverClassName=org.h2.Driver

# Dialeto JPA
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Atualiza tabelas sem apagar dados
spring.jpa.hibernate.ddl-auto=update

spring.h2.console.path=/h2-console
server.port=5002